const exampleId=new URLSearchParams(location.search).get('id');const currentPortfolio=window.LOCAL_DATA.portfolios.find(p=>p.portfolio_id===exampleId);const portfolioClient=window.LOCAL_DATA.clients.find(c=>c.client_id===currentPortfolio?.client_id);const clientNotes=window.LOCAL_DATA.notes?.filter(n=>n.client_id===portfolioClient?.client_id).sort((a,b)=>new Date(b.note_date)-new Date(a.note_date));const lastMeeting=clientNotes?.find(n=>n.channel==='Meeting');
if(exampleId==='PF-0016'){
document.querySelector('.movement-grid').innerHTML='<article class="movement-card"><div class="movement-symbol">A</div><div><h3>Asia High Yield Bond Fund</h3><p>Fixed income · illustrative movement</p></div><strong class="down">−8.6%</strong></article><article class="reason-card"><span>EVENT LOG · 30 APR 2026</span><h3>Central banks raised policy rates</h3><p>Rates were raised in response to an energy-driven inflation impulse, putting pressure on longer-duration and higher-yield credit.</p></article><article class="movement-card"><div class="movement-symbol">B</div><div><h3>Pacific Rim Bank Perpetual</h3><p>Fixed income · illustrative movement</p></div><strong class="down">−5.2%</strong></article><article class="reason-card"><span>EVENT LOG · 30 JUN 2026</span><h3>Redemption stress in private credit</h3><p>Continued redemption stress across non-traded private-credit vehicles weakened sentiment across parts of the credit market.</p></article>';
document.querySelector('.options-grid').innerHTML='<article class="option-card urgent-option"><span class="option-number">01 · URGENT</span><h3>Pay down existing credit facility</h3><p>Ask whether outside cash is available to reduce the $58M drawn on CF-0002.</p><div class="action"><b>RM · 02 Sep 2026</b><span>Ask client about available cash.</span></div><div class="action"><b>RM · 05 Sep 2026</b><span>Calculate paydown needed to bring LTV below 60%.</span></div></article><article class="option-card"><span class="option-number">02</span><h3>Sell a small slice of bonds</h3><p>Fund near-term withdrawals while addressing the duration breach.</p><div class="action"><b>RM · 10 Sep 2026</b><span>Identify shortest-duration bonds and calculate the loss.</span></div><div class="action"><b>IC/Risk · 15 Sep 2026</b><span>Log the trade for mandate-breach review.</span></div></article>';
}
if(document.querySelector('#movementPeriod'))document.querySelector('#movementPeriod').textContent=lastMeeting?'Since last meeting · '+new Date(lastMeeting.note_date+'T00:00:00').toLocaleDateString('en-SG',{day:'numeric',month:'short',year:'numeric'}):'Last 30 days';
document.querySelectorAll('.option-card').forEach(card=>{const steps=card.querySelectorAll('.action');if(!steps.length)return;const toggle=document.createElement('button');toggle.className='action-toggle';toggle.textContent='View action steps ⌄';card.insertBefore(toggle,steps[0]);toggle.addEventListener('click',e=>{e.stopPropagation();const open=card.classList.toggle('open');toggle.textContent=open?'Hide action steps ⌃':'View action steps ⌄';});});
if(exampleId==='PF-0010'){document.querySelector('.movement-grid').innerHTML='<article class="movement-card"><div class="movement-symbol">N</div><div><h3>NVIDIA Corp.</h3><p>5 Jun 2026 · AI capex concerns</p></div><strong class="down">−7.8%</strong></article><article class="reason-card"><span>EVENT LOG · 5 JUN 2026</span><h3>Technology sell-off</h3><p>The megacap technology complex briefly lost around USD 2T in market value as investors questioned the pace of AI capital expenditure.</p></article><article class="movement-card"><div class="movement-symbol">N</div><div><h3>NVIDIA Corp.</h3><p>19 Jun 2026 · Treasury yields</p></div><strong class="down">−4.1%</strong></article><article class="reason-card"><span>EVENT LOG · 19 JUN 2026</span><h3>Higher bond yields</h3><p>The US 10-year Treasury yield rose to about 4.46%, putting renewed pressure on long-duration growth stocks.</p></article><article class="movement-card"><div class="movement-symbol">N</div><div><h3>NVIDIA Corp.</h3><p>30 Jun 2026 · Half-year close</p></div><strong class="up">+6.3%</strong></article><article class="reason-card"><span>EVENT LOG · 30 JUN 2026</span><h3>Technology-led recovery</h3><p>US equities ended the half-year near record levels, supported by renewed leadership from large technology companies.</p></article>';}
if(document.querySelector('.movement-grid')){const grid=document.querySelector('.movement-grid');grid.insertAdjacentHTML('beforebegin','<div class="movement-subheading">SHARP MOVES</div>');grid.insertAdjacentHTML('afterend','<div class="trend-block"><div class="movement-subheading">GENERAL TREND</div><div class="trend-card"><span class="trend-line">↗</span><div><h3>Portfolio trend over selected period</h3><p>Overall direction and performance summary will be presented here, using the portfolio holdings and the period shown above.</p></div><strong>Pending analysis</strong></div></div>');}
if(exampleId==='PF-0016'){document.querySelector('.movement-grid').innerHTML='<div class="empty-moves">No separate sharp holding moves recorded for this period.</div>';document.querySelector('.portfolio-hero').classList.add('hero-with-alert');document.querySelector('.portfolio-hero').insertAdjacentHTML('beforeend','<div class="hero-alert"><span>URGENT</span><b>Duration outside mandate</b><small>9.2 years · maximum 7 years</small></div>');}
if(exampleId==='PF-0016'){document.querySelector('.trend-card').outerHTML='<div class="trend-card trend-list"><div class="trend-item"><span class="trend-line">↘</span><div><h3>Asia High Yield Bond Fund</h3><p>General trend · weakening over the selected period</p></div><strong>−8.6%</strong></div><div class="trend-item"><span class="trend-line">↘</span><div><h3>Pacific Rim Bank Perpetual</h3><p>General trend · weakening over the selected period</p></div><strong>−5.2%</strong></div></div>';}
if(currentPortfolio?.service_model==='Advisory'||currentPortfolio?.service_model==='Discretionary'){const loading=document.querySelectorAll('.movement-grid,.trend-card,.options-grid');loading.forEach(item=>item.classList.add('data-loading'));setTimeout(()=>loading.forEach(item=>{item.classList.remove('data-loading');item.classList.add('data-ready')}),2000);}
if(exampleId==='PF-0016'){const rationales=['LTV is at 69.41%, only 0.59 points from the 70% margin call trigger — this is more urgent than the paper loss because the bank could force-sell holdings automatically if it is not addressed.','Projected income over the next 3 years falls short of planned withdrawals by $900,000 — selling a small slice now covers this gap on the client\'s own terms rather than a forced sale later.'];document.querySelectorAll('.option-card').forEach((card,i)=>{const toggle=document.createElement('button');toggle.className='rationale-toggle';toggle.textContent='View rationale ⌄';const body=document.createElement('div');body.className='rationale-body';body.textContent=rationales[i];card.append(toggle,body);toggle.addEventListener('click',e=>{e.stopPropagation();const open=card.classList.toggle('rationale-open');toggle.textContent=open?'Hide rationale ⌃':'View rationale ⌄';});});}



